<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201104144117 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alarm_test (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, date DATETIME NOT NULL, local TINYINT(1) NOT NULL, remote TINYINT(1) NOT NULL, comments LONGTEXT NOT NULL, INDEX IDX_F75CF1217E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alarm_test_buildings (alarm_test_id INT NOT NULL, buildings_id INT NOT NULL, INDEX IDX_558F4A5330B42433 (alarm_test_id), INDEX IDX_558F4A531485E613 (buildings_id), PRIMARY KEY(alarm_test_id, buildings_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alarm_test_person (alarm_test_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_9CB9C2B530B42433 (alarm_test_id), INDEX IDX_9CB9C2B5217BBB47 (person_id), PRIMARY KEY(alarm_test_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE beeding (id INT AUTO_INCREMENT NOT NULL, padding_id INT NOT NULL, herd_id INT NOT NULL, person_id INT NOT NULL, date DATE NOT NULL, quantity INT NOT NULL, iu VARCHAR(5) NOT NULL, INDEX IDX_5344C64F438BFA98 (padding_id), INDEX IDX_5344C64FD35A8CCC (herd_id), INDEX IDX_5344C64F217BBB47 (person_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clean_building (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, date DATETIME NOT NULL, quantity DOUBLE PRECISION NOT NULL, INDEX IDX_726DE6A97E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clean_building_buildings (clean_building_id INT NOT NULL, buildings_id INT NOT NULL, INDEX IDX_FBB5BAA88BCFEA22 (clean_building_id), INDEX IDX_FBB5BAA81485E613 (buildings_id), PRIMARY KEY(clean_building_id, buildings_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clean_building_detergent (clean_building_id INT NOT NULL, detergent_id INT NOT NULL, INDEX IDX_999E8AD58BCFEA22 (clean_building_id), INDEX IDX_999E8AD53B56D2C1 (detergent_id), PRIMARY KEY(clean_building_id, detergent_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clean_building_person (clean_building_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_7F55833C8BCFEA22 (clean_building_id), INDEX IDX_7F55833C217BBB47 (person_id), PRIMARY KEY(clean_building_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE detergent (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, name VARCHAR(100) NOT NULL, INDEX IDX_F87A86DA7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disinfectant (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_3C540D337E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disinfection_building (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, date DATETIME NOT NULL, quantity DOUBLE PRECISION NOT NULL, INDEX IDX_103A7F1F7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disinfection_building_buildings (disinfection_building_id INT NOT NULL, buildings_id INT NOT NULL, INDEX IDX_5DA112A01F909DE6 (disinfection_building_id), INDEX IDX_5DA112A01485E613 (buildings_id), PRIMARY KEY(disinfection_building_id, buildings_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disinfection_building_disinfectant (disinfection_building_id INT NOT NULL, disinfectant_id INT NOT NULL, INDEX IDX_4ECD90801F909DE6 (disinfection_building_id), INDEX IDX_4ECD908099C47565 (disinfectant_id), PRIMARY KEY(disinfection_building_id, disinfectant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disinfection_building_person (disinfection_building_id INT NOT NULL, person_id INT NOT NULL, INDEX IDX_1D85927E1F909DE6 (disinfection_building_id), INDEX IDX_1D85927E217BBB47 (person_id), PRIMARY KEY(disinfection_building_id, person_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disinfection_place (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_5999EBE47E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE herd_disinfection (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, date DATETIME NOT NULL, quantity DOUBLE PRECISION NOT NULL, INDEX IDX_A7B862287E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE herd_disinfection_herds (herd_disinfection_id INT NOT NULL, herds_id INT NOT NULL, INDEX IDX_7AB49CC1C26EE054 (herd_disinfection_id), INDEX IDX_7AB49CC175706932 (herds_id), PRIMARY KEY(herd_disinfection_id, herds_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE herd_disinfection_disinfection_place (herd_disinfection_id INT NOT NULL, disinfection_place_id INT NOT NULL, INDEX IDX_E7302565C26EE054 (herd_disinfection_id), INDEX IDX_E7302565FCF3BCD2 (disinfection_place_id), PRIMARY KEY(herd_disinfection_id, disinfection_place_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE herd_disinfection_disinfectant (herd_disinfection_id INT NOT NULL, disinfectant_id INT NOT NULL, INDEX IDX_E5D78BFBC26EE054 (herd_disinfection_id), INDEX IDX_E5D78BFB99C47565 (disinfectant_id), PRIMARY KEY(herd_disinfection_id, disinfectant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, firms_id INT NOT NULL, owner_id INT NOT NULL, first_name VARCHAR(100) NOT NULL, sur_name VARCHAR(100) NOT NULL, phone_number VARCHAR(20) DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, INDEX IDX_34DCD176AA4A7305 (firms_id), INDEX IDX_34DCD1767E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE alarm_test ADD CONSTRAINT FK_F75CF1217E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE alarm_test_buildings ADD CONSTRAINT FK_558F4A5330B42433 FOREIGN KEY (alarm_test_id) REFERENCES alarm_test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alarm_test_buildings ADD CONSTRAINT FK_558F4A531485E613 FOREIGN KEY (buildings_id) REFERENCES buildings (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alarm_test_person ADD CONSTRAINT FK_9CB9C2B530B42433 FOREIGN KEY (alarm_test_id) REFERENCES alarm_test (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alarm_test_person ADD CONSTRAINT FK_9CB9C2B5217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE beeding ADD CONSTRAINT FK_5344C64F438BFA98 FOREIGN KEY (padding_id) REFERENCES paddings (id)');
        $this->addSql('ALTER TABLE beeding ADD CONSTRAINT FK_5344C64FD35A8CCC FOREIGN KEY (herd_id) REFERENCES herds (id)');
        $this->addSql('ALTER TABLE beeding ADD CONSTRAINT FK_5344C64F217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
        $this->addSql('ALTER TABLE clean_building ADD CONSTRAINT FK_726DE6A97E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE clean_building_buildings ADD CONSTRAINT FK_FBB5BAA88BCFEA22 FOREIGN KEY (clean_building_id) REFERENCES clean_building (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clean_building_buildings ADD CONSTRAINT FK_FBB5BAA81485E613 FOREIGN KEY (buildings_id) REFERENCES buildings (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clean_building_detergent ADD CONSTRAINT FK_999E8AD58BCFEA22 FOREIGN KEY (clean_building_id) REFERENCES clean_building (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clean_building_detergent ADD CONSTRAINT FK_999E8AD53B56D2C1 FOREIGN KEY (detergent_id) REFERENCES detergent (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clean_building_person ADD CONSTRAINT FK_7F55833C8BCFEA22 FOREIGN KEY (clean_building_id) REFERENCES clean_building (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE clean_building_person ADD CONSTRAINT FK_7F55833C217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE detergent ADD CONSTRAINT FK_F87A86DA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE disinfectant ADD CONSTRAINT FK_3C540D337E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE disinfection_building ADD CONSTRAINT FK_103A7F1F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE disinfection_building_buildings ADD CONSTRAINT FK_5DA112A01F909DE6 FOREIGN KEY (disinfection_building_id) REFERENCES disinfection_building (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disinfection_building_buildings ADD CONSTRAINT FK_5DA112A01485E613 FOREIGN KEY (buildings_id) REFERENCES buildings (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disinfection_building_disinfectant ADD CONSTRAINT FK_4ECD90801F909DE6 FOREIGN KEY (disinfection_building_id) REFERENCES disinfection_building (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disinfection_building_disinfectant ADD CONSTRAINT FK_4ECD908099C47565 FOREIGN KEY (disinfectant_id) REFERENCES disinfectant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disinfection_building_person ADD CONSTRAINT FK_1D85927E1F909DE6 FOREIGN KEY (disinfection_building_id) REFERENCES disinfection_building (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disinfection_building_person ADD CONSTRAINT FK_1D85927E217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disinfection_place ADD CONSTRAINT FK_5999EBE47E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE herd_disinfection ADD CONSTRAINT FK_A7B862287E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE herd_disinfection_herds ADD CONSTRAINT FK_7AB49CC1C26EE054 FOREIGN KEY (herd_disinfection_id) REFERENCES herd_disinfection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE herd_disinfection_herds ADD CONSTRAINT FK_7AB49CC175706932 FOREIGN KEY (herds_id) REFERENCES herds (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE herd_disinfection_disinfection_place ADD CONSTRAINT FK_E7302565C26EE054 FOREIGN KEY (herd_disinfection_id) REFERENCES herd_disinfection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE herd_disinfection_disinfection_place ADD CONSTRAINT FK_E7302565FCF3BCD2 FOREIGN KEY (disinfection_place_id) REFERENCES disinfection_place (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE herd_disinfection_disinfectant ADD CONSTRAINT FK_E5D78BFBC26EE054 FOREIGN KEY (herd_disinfection_id) REFERENCES herd_disinfection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE herd_disinfection_disinfectant ADD CONSTRAINT FK_E5D78BFB99C47565 FOREIGN KEY (disinfectant_id) REFERENCES disinfectant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176AA4A7305 FOREIGN KEY (firms_id) REFERENCES firms (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1767E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE breed_line DROP FOREIGN KEY FK_703EE4497E3C61F9');
        $this->addSql('DROP INDEX IDX_703EE4497E3C61F9 ON breed_line');
        $this->addSql('ALTER TABLE breed_line DROP owner_id');
        $this->addSql('ALTER TABLE breed_line_standard DROP FOREIGN KEY FK_B8E2DFEE7E3C61F9');
        $this->addSql('DROP INDEX IDX_B8E2DFEE7E3C61F9 ON breed_line_standard');
        $this->addSql('ALTER TABLE breed_line_standard DROP owner_id');
        $this->addSql('ALTER TABLE breeds DROP FOREIGN KEY FK_FD953C827E3C61F9');
        $this->addSql('DROP INDEX IDX_FD953C827E3C61F9 ON breeds');
        $this->addSql('ALTER TABLE breeds DROP owner_id');
        $this->addSql('ALTER TABLE buildings DROP FOREIGN KEY FK_9A51B6A77E3C61F9');
        $this->addSql('DROP INDEX IDX_9A51B6A77E3C61F9 ON buildings');
        $this->addSql('ALTER TABLE buildings DROP owner_id');
        $this->addSql('ALTER TABLE certificate DROP FOREIGN KEY FK_219CDA4A7E3C61F9');
        $this->addSql('DROP INDEX IDX_219CDA4A7E3C61F9 ON certificate');
        $this->addSql('ALTER TABLE certificate DROP owner_id');
        $this->addSql('ALTER TABLE certificate_type DROP FOREIGN KEY FK_F2C76A507E3C61F9');
        $this->addSql('DROP INDEX IDX_F2C76A507E3C61F9 ON certificate_type');
        $this->addSql('ALTER TABLE certificate_type DROP owner_id');
        $this->addSql('ALTER TABLE counter DROP FOREIGN KEY FK_C12294787E3C61F9');
        $this->addSql('DROP INDEX IDX_C12294787E3C61F9 ON counter');
        $this->addSql('ALTER TABLE counter DROP owner_id');
        $this->addSql('ALTER TABLE counter_state DROP FOREIGN KEY FK_700AABD97E3C61F9');
        $this->addSql('DROP INDEX IDX_700AABD97E3C61F9 ON counter_state');
        $this->addSql('ALTER TABLE counter_state DROP owner_id');
        $this->addSql('ALTER TABLE counter_type DROP FOREIGN KEY FK_C3538E4E7E3C61F9');
        $this->addSql('DROP INDEX IDX_C3538E4E7E3C61F9 ON counter_type');
        $this->addSql('ALTER TABLE counter_type DROP owner_id');
        $this->addSql('ALTER TABLE farm DROP FOREIGN KEY FK_5816D0457E3C61F9');
        $this->addSql('DROP INDEX IDX_5816D0457E3C61F9 ON farm');
        $this->addSql('ALTER TABLE farm DROP owner_id');
        $this->addSql('ALTER TABLE firm_type DROP FOREIGN KEY FK_DE905AB97E3C61F9');
        $this->addSql('DROP INDEX IDX_DE905AB97E3C61F9 ON firm_type');
        $this->addSql('ALTER TABLE firm_type DROP owner_id');
        $this->addSql('ALTER TABLE firms DROP FOREIGN KEY FK_D854442B7E3C61F9');
        $this->addSql('DROP INDEX IDX_D854442B7E3C61F9 ON firms');
        $this->addSql('ALTER TABLE firms DROP owner_id');
        $this->addSql('ALTER TABLE herds DROP FOREIGN KEY FK_FC70FEBB7E3C61F9');
        $this->addSql('DROP INDEX IDX_FC70FEBB7E3C61F9 ON herds');
        $this->addSql('ALTER TABLE herds DROP owner_id');
        $this->addSql('ALTER TABLE herds_data DROP FOREIGN KEY FK_1D801D087E3C61F9');
        $this->addSql('DROP INDEX IDX_1D801D087E3C61F9 ON herds_data');
        $this->addSql('ALTER TABLE herds_data DROP owner_id');
        $this->addSql('ALTER TABLE lights DROP FOREIGN KEY FK_38BCB2E87E3C61F9');
        $this->addSql('DROP INDEX IDX_38BCB2E87E3C61F9 ON lights');
        $this->addSql('ALTER TABLE lights DROP owner_id');
        $this->addSql('ALTER TABLE paddings DROP FOREIGN KEY FK_FCB3162C7E3C61F9');
        $this->addSql('DROP INDEX IDX_FCB3162C7E3C61F9 ON paddings');
        $this->addSql('ALTER TABLE paddings DROP owner_id');
        $this->addSql('ALTER TABLE provide_supplement DROP FOREIGN KEY FK_D85008B67E3C61F9');
        $this->addSql('DROP INDEX IDX_D85008B67E3C61F9 ON provide_supplement');
        $this->addSql('ALTER TABLE provide_supplement CHANGE owner_id person_id INT NOT NULL');
        $this->addSql('ALTER TABLE provide_supplement ADD CONSTRAINT FK_D85008B6217BBB47 FOREIGN KEY (person_id) REFERENCES person (id)');
        $this->addSql('CREATE INDEX IDX_D85008B6217BBB47 ON provide_supplement (person_id)');
        $this->addSql('ALTER TABLE silo DROP FOREIGN KEY FK_B8D78A37E3C61F9');
        $this->addSql('DROP INDEX IDX_B8D78A37E3C61F9 ON silo');
        $this->addSql('ALTER TABLE silo DROP owner_id');
        $this->addSql('ALTER TABLE silo_refueling DROP FOREIGN KEY FK_D2E3F3877E3C61F9');
        $this->addSql('DROP INDEX IDX_D2E3F3877E3C61F9 ON silo_refueling');
        $this->addSql('ALTER TABLE silo_refueling DROP owner_id');
        $this->addSql('ALTER TABLE silo_type DROP FOREIGN KEY FK_42EE1B1F7E3C61F9');
        $this->addSql('DROP INDEX IDX_42EE1B1F7E3C61F9 ON silo_type');
        $this->addSql('ALTER TABLE silo_type DROP owner_id');
        $this->addSql('ALTER TABLE supplement DROP FOREIGN KEY FK_15A73C97E3C61F9');
        $this->addSql('DROP INDEX IDX_15A73C97E3C61F9 ON supplement');
        $this->addSql('ALTER TABLE supplement DROP owner_id');
        $this->addSql('ALTER TABLE tank DROP FOREIGN KEY FK_AD12B7397E3C61F9');
        $this->addSql('DROP INDEX IDX_AD12B7397E3C61F9 ON tank');
        $this->addSql('ALTER TABLE tank DROP owner_id');
        $this->addSql('ALTER TABLE tank_state DROP FOREIGN KEY FK_8389ED217E3C61F9');
        $this->addSql('DROP INDEX IDX_8389ED217E3C61F9 ON tank_state');
        $this->addSql('ALTER TABLE tank_state DROP owner_id');
        $this->addSql('ALTER TABLE tank_type DROP FOREIGN KEY FK_F9643E5C7E3C61F9');
        $this->addSql('DROP INDEX IDX_F9643E5C7E3C61F9 ON tank_type');
        $this->addSql('ALTER TABLE tank_type DROP owner_id');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alarm_test_buildings DROP FOREIGN KEY FK_558F4A5330B42433');
        $this->addSql('ALTER TABLE alarm_test_person DROP FOREIGN KEY FK_9CB9C2B530B42433');
        $this->addSql('ALTER TABLE clean_building_buildings DROP FOREIGN KEY FK_FBB5BAA88BCFEA22');
        $this->addSql('ALTER TABLE clean_building_detergent DROP FOREIGN KEY FK_999E8AD58BCFEA22');
        $this->addSql('ALTER TABLE clean_building_person DROP FOREIGN KEY FK_7F55833C8BCFEA22');
        $this->addSql('ALTER TABLE clean_building_detergent DROP FOREIGN KEY FK_999E8AD53B56D2C1');
        $this->addSql('ALTER TABLE disinfection_building_disinfectant DROP FOREIGN KEY FK_4ECD908099C47565');
        $this->addSql('ALTER TABLE herd_disinfection_disinfectant DROP FOREIGN KEY FK_E5D78BFB99C47565');
        $this->addSql('ALTER TABLE disinfection_building_buildings DROP FOREIGN KEY FK_5DA112A01F909DE6');
        $this->addSql('ALTER TABLE disinfection_building_disinfectant DROP FOREIGN KEY FK_4ECD90801F909DE6');
        $this->addSql('ALTER TABLE disinfection_building_person DROP FOREIGN KEY FK_1D85927E1F909DE6');
        $this->addSql('ALTER TABLE herd_disinfection_disinfection_place DROP FOREIGN KEY FK_E7302565FCF3BCD2');
        $this->addSql('ALTER TABLE herd_disinfection_herds DROP FOREIGN KEY FK_7AB49CC1C26EE054');
        $this->addSql('ALTER TABLE herd_disinfection_disinfection_place DROP FOREIGN KEY FK_E7302565C26EE054');
        $this->addSql('ALTER TABLE herd_disinfection_disinfectant DROP FOREIGN KEY FK_E5D78BFBC26EE054');
        $this->addSql('ALTER TABLE alarm_test_person DROP FOREIGN KEY FK_9CB9C2B5217BBB47');
        $this->addSql('ALTER TABLE beeding DROP FOREIGN KEY FK_5344C64F217BBB47');
        $this->addSql('ALTER TABLE clean_building_person DROP FOREIGN KEY FK_7F55833C217BBB47');
        $this->addSql('ALTER TABLE disinfection_building_person DROP FOREIGN KEY FK_1D85927E217BBB47');
        $this->addSql('ALTER TABLE provide_supplement DROP FOREIGN KEY FK_D85008B6217BBB47');
        $this->addSql('DROP TABLE alarm_test');
        $this->addSql('DROP TABLE alarm_test_buildings');
        $this->addSql('DROP TABLE alarm_test_person');
        $this->addSql('DROP TABLE beeding');
        $this->addSql('DROP TABLE clean_building');
        $this->addSql('DROP TABLE clean_building_buildings');
        $this->addSql('DROP TABLE clean_building_detergent');
        $this->addSql('DROP TABLE clean_building_person');
        $this->addSql('DROP TABLE detergent');
        $this->addSql('DROP TABLE disinfectant');
        $this->addSql('DROP TABLE disinfection_building');
        $this->addSql('DROP TABLE disinfection_building_buildings');
        $this->addSql('DROP TABLE disinfection_building_disinfectant');
        $this->addSql('DROP TABLE disinfection_building_person');
        $this->addSql('DROP TABLE disinfection_place');
        $this->addSql('DROP TABLE herd_disinfection');
        $this->addSql('DROP TABLE herd_disinfection_herds');
        $this->addSql('DROP TABLE herd_disinfection_disinfection_place');
        $this->addSql('DROP TABLE herd_disinfection_disinfectant');
        $this->addSql('DROP TABLE person');
        $this->addSql('ALTER TABLE breed_line ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE breed_line ADD CONSTRAINT FK_703EE4497E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_703EE4497E3C61F9 ON breed_line (owner_id)');
        $this->addSql('ALTER TABLE breed_line_standard ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE breed_line_standard ADD CONSTRAINT FK_B8E2DFEE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_B8E2DFEE7E3C61F9 ON breed_line_standard (owner_id)');
        $this->addSql('ALTER TABLE breeds ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE breeds ADD CONSTRAINT FK_FD953C827E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_FD953C827E3C61F9 ON breeds (owner_id)');
        $this->addSql('ALTER TABLE buildings ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE buildings ADD CONSTRAINT FK_9A51B6A77E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_9A51B6A77E3C61F9 ON buildings (owner_id)');
        $this->addSql('ALTER TABLE certificate ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE certificate ADD CONSTRAINT FK_219CDA4A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_219CDA4A7E3C61F9 ON certificate (owner_id)');
        $this->addSql('ALTER TABLE certificate_type ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE certificate_type ADD CONSTRAINT FK_F2C76A507E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_F2C76A507E3C61F9 ON certificate_type (owner_id)');
        $this->addSql('ALTER TABLE counter ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE counter ADD CONSTRAINT FK_C12294787E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_C12294787E3C61F9 ON counter (owner_id)');
        $this->addSql('ALTER TABLE counter_state ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE counter_state ADD CONSTRAINT FK_700AABD97E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_700AABD97E3C61F9 ON counter_state (owner_id)');
        $this->addSql('ALTER TABLE counter_type ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE counter_type ADD CONSTRAINT FK_C3538E4E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_C3538E4E7E3C61F9 ON counter_type (owner_id)');
        $this->addSql('ALTER TABLE farm ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE farm ADD CONSTRAINT FK_5816D0457E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_5816D0457E3C61F9 ON farm (owner_id)');
        $this->addSql('ALTER TABLE firm_type ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE firm_type ADD CONSTRAINT FK_DE905AB97E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_DE905AB97E3C61F9 ON firm_type (owner_id)');
        $this->addSql('ALTER TABLE firms ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE firms ADD CONSTRAINT FK_D854442B7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_D854442B7E3C61F9 ON firms (owner_id)');
        $this->addSql('ALTER TABLE herds ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE herds ADD CONSTRAINT FK_FC70FEBB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_FC70FEBB7E3C61F9 ON herds (owner_id)');
        $this->addSql('ALTER TABLE herds_data ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE herds_data ADD CONSTRAINT FK_1D801D087E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_1D801D087E3C61F9 ON herds_data (owner_id)');
        $this->addSql('ALTER TABLE lights ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE lights ADD CONSTRAINT FK_38BCB2E87E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_38BCB2E87E3C61F9 ON lights (owner_id)');
        $this->addSql('ALTER TABLE paddings ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE paddings ADD CONSTRAINT FK_FCB3162C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_FCB3162C7E3C61F9 ON paddings (owner_id)');
        $this->addSql('DROP INDEX IDX_D85008B6217BBB47 ON provide_supplement');
        $this->addSql('ALTER TABLE provide_supplement CHANGE person_id owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE provide_supplement ADD CONSTRAINT FK_D85008B67E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_D85008B67E3C61F9 ON provide_supplement (owner_id)');
        $this->addSql('ALTER TABLE silo ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE silo ADD CONSTRAINT FK_B8D78A37E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_B8D78A37E3C61F9 ON silo (owner_id)');
        $this->addSql('ALTER TABLE silo_refueling ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE silo_refueling ADD CONSTRAINT FK_D2E3F3877E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_D2E3F3877E3C61F9 ON silo_refueling (owner_id)');
        $this->addSql('ALTER TABLE silo_type ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE silo_type ADD CONSTRAINT FK_42EE1B1F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_42EE1B1F7E3C61F9 ON silo_type (owner_id)');
        $this->addSql('ALTER TABLE supplement ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE supplement ADD CONSTRAINT FK_15A73C97E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_15A73C97E3C61F9 ON supplement (owner_id)');
        $this->addSql('ALTER TABLE tank ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE tank ADD CONSTRAINT FK_AD12B7397E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_AD12B7397E3C61F9 ON tank (owner_id)');
        $this->addSql('ALTER TABLE tank_state ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE tank_state ADD CONSTRAINT FK_8389ED217E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_8389ED217E3C61F9 ON tank_state (owner_id)');
        $this->addSql('ALTER TABLE tank_type ADD owner_id INT NOT NULL');
        $this->addSql('ALTER TABLE tank_type ADD CONSTRAINT FK_F9643E5C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_F9643E5C7E3C61F9 ON tank_type (owner_id)');
    }
}
