#index:
#    path: /
#    controller: App\Controller\DefaultController::index
herds_get_quantity:
  path: api/herds/{id}/quantity
  methods: 'GET'
  defaults:
    _controller: App\Controller\HerdsController::stateMainPage
    _api_resource_class: App\Entity\Herds
    _api_item_operation_name: herds_get_quantity